const fabricImages = {
    "Shema": "/images/fabrics/shema_ethiopia.png",
    "Lawo (parure nilotique)": "/images/fabrics/lawo_south_sudan.png",
    "Guntiino": "/images/fabrics/guntiino_somalia.png",
    "Shuka masaï": "/images/fabrics/shuka_kenya.png",
    "Kanga": "/images/fabrics/kanga_kenya.png",
    "Chitenje": "/images/fabrics/chitenje_malawi.png",
    "Sabra (soie de cactus)": "/images/fabrics/sabra_morocco.png",
    "Kita": "/images/fabrics/kita_congo.png",
    "Raphia Kuba": "/images/fabrics/raphia_kuba_drc.png",
    "Odelela": "/images/fabrics/odelela_namibia.png",
    "Shweshwe": "/images/fabrics/shweshwe_south_africa.png",
    "Umbhaco": "/images/fabrics/umbhaco_south_africa.png",
    "Jard (houli)": "/images/fabrics/jard_libya.png",
    "Sefsari": "/images/fabrics/sefsari_tunisia.png",
    "Chitenge": "/images/fabrics/chitenge_zambia.png",
    "Gara (Tie & Dye)": "/images/fabrics/gara_sierra_leone.png",
    "Lépi": "/images/fabrics/lepi_guinea.png",
    "Forêt sacrée": "/images/fabrics/foret_sacree_guinea.png",
    "Country Cloth": "/images/fabrics/country_cloth_liberia.png",
    "Étoffe d'écorce": "/images/fabrics/ecorce_central_africa.png",
    "Thobe (toub)": "/images/fabrics/thobe_sudan.png",
    "Futa (léfio)": "/images/fabrics/futa_djibouti.png",
    "Zuria (Habesha)": "/images/fabrics/zuria_eritrea.png",
    "Pagne baoulé": "/images/fabrics/pagne_baoule_ivory_coast.png",
    "Bogolan": "/images/fabrics/bogolan_mali.png",
    "Bazin riche": "/images/fabrics/bazin_senegal.png",
    "Thioup (tie-dye)": "/images/fabrics/thioup_senegal.png",
    "Aso Oke": "/images/fabrics/aso_oke_nigeria.png",
    "Kanvô": "/images/fabrics/kanvo_benin.png",
    "Samakaka": "/images/fabrics/samakaka_angola.png",
    "Leteisi (Shweshwe)": "/images/fabrics/leteisi_botswana.png",
    "Mutapa": "/images/fabrics/mutapa_zimbabwe.png",
    "Godong (Gabak)": "/images/fabrics/godong_tchad.png",
    "Burnous": "/images/fabrics/burnous_algeria.png",
    "Capulana": "/images/fabrics/capulana_mozambique.png",
    "Emahiya (Lihiya)": "/images/fabrics/emahiya_eswatini.png",
    "Imvutano (Pagne traditionnel)": "/images/fabrics/imvutano_burundi.png",
    "Imigongo": "/images/fabrics/imigongo_rwanda.png",
    "Lubugo (tissu d'écorce)": "/images/fabrics/lubugo_uganda.png",
    "Couverture basotho": "/images/fabrics/basotho_lesotho.png",
    "Ndop": "/images/fabrics/ndop_cameroun.png",
    "Toghu": "/images/fabrics/toghu_cameroun.png",
    "Raphia et wax": "/images/fabrics/raphia_wax_gabon.png",
    "Strip-weave (pagne tissé)": "/images/fabrics/strip_weave_niger.png",
    "Faso Dan Fani": "/images/fabrics/faso_dan_fani_burkina.png",
    "Koko Dunda": "/images/fabrics/koko_dunda_burkina.png",
    "Batik": "/images/fabrics/batik_togo.png",
    "Kenté": "/images/fabrics/kente_ghana.png",
    "Adinkra": "/images/fabrics/adinkra_ghana.png",
    "Pagne Manjak": "/images/fabrics/pagne_manjak_guinea_bissau.png",
    "Khayamiya": "/images/fabrics/khayamiya_egypt.png",
    "Mélhafa": "/images/fabrics/melhafa_mauritania.png",
    "Pagne Fang": "/images/fabrics/pagne_fang_guinea_equatorial.png",
    "Gara et pagne Manjak": "/images/fabrics/gara_manjak_gambia.png",
    "Lamba": "/images/fabrics/lamba_madagascar.png",
    "Chiromani": "/images/fabrics/chiromani_comoros.png",
    "Pagne Santoméen": "/images/fabrics/pagne_sao_tome.png",
    "Pano di terra": "/images/fabrics/pano_cap_vert.png"
  };
  