
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.productImage.createMany({
    data: [
      { url: '/uploads/products/fdf-c-10/studio.jpg', altText: 'Studio du tissu fdf-c-10', productId: 58 },
      { url: '/uploads/products/fdf-c-10/zoom.jpg', altText: 'Zoom du tissu fdf-c-10', productId: 58 },
      { url: '/uploads/products/fdf-c-10/deco.jpg', altText: 'Deco du tissu fdf-c-10', productId: 58 },
      { url: '/uploads/products/fdf-c-10/mode.jpg', altText: 'Mode du tissu fdf-c-10', productId: 58 },
      { url: '/uploads/products/bog-afritex-11/studio.png', altText: 'Studio du tissu bog-afritex-11', productId: 1 },
      { url: '/uploads/products/bog-afritex-11/zoom.png', altText: 'Zoom du tissu bog-afritex-11', productId: 1 },
      { url: '/uploads/products/bog-afritex-11/deco.png', altText: 'Deco du tissu bog-afritex-11', productId: 1 },
      { url: '/uploads/products/bog-afritex-11/mode.png', altText: 'Mode du tissu bog-afritex-11', productId: 1 },
      { url: '/uploads/products/bog-afritex-12-fixed/studio.png', altText: 'Studio du tissu bog-afritex-12-fixed', productId: 7 },
      { url: '/uploads/products/bog-afritex-12-fixed/zoom.png', altText: 'Zoom du tissu bog-afritex-12-fixed', productId: 7 },
      { url: '/uploads/products/bog-afritex-12-fixed/deco.png', altText: 'Deco du tissu bog-afritex-12-fixed', productId: 7 },
      { url: '/uploads/products/bog-afritex-12-fixed/mode.png', altText: 'Mode du tissu bog-afritex-12-fixed', productId: 7 },
      { url: '/uploads/products/bog-afritex-14/studio.png', altText: 'Studio du tissu bog-afritex-14', productId: 9},
      { url: '/uploads/products/bog-afritex-14/zoom.png', altText: 'Zoom du tissu bog-afritex-14', productId: 9 },
      { url: '/uploads/products/bog-afritex-14/deco.png', altText: 'Deco du tissu bog-afritex-14', productId:9 },
      { url: '/uploads/products/bog-afritex-14/mode.png', altText: 'Mode du tissu bog-afritex-14', productId: 9},
      { url: '/uploads/products/bog-afritex-15/studio.png', altText: 'Studio du tissu bog-afritex-15', productId: 10 },
      { url: '/uploads/products/bog-afritex-15/zoom.png', altText: 'Zoom du tissu bog-afritex-15', productId: 10},
      { url: '/uploads/products/bog-afritex-15/deco.png', altText: 'Deco du tissu bog-afritex-15', productId:10 },
      { url: '/uploads/products/bog-afritex-15/mode.png', altText: 'Mode du tissu bog-afritex-15', productId:10},
      { url: '/uploads/products/bog-afritex-16/studio.png', altText: 'Studio du tissu bog-afritex-16', productId: 12},
      { url: '/uploads/products/bog-afritex-16/zoom.png', altText: 'Zoom du tissu bog-afritex-16', productId: 12},
      { url: '/uploads/products/bog-afritex-16/deco.png', altText: 'Deco du tissu bog-afritex-16', productId: 12 },
      { url: '/uploads/products/bog-afritex-16/mode.png', altText: 'Mode du tissu bog-afritex-16', productId: 12 },
      { url: '/uploads/products/bog-afritex-18/studio.png', altText: 'Studio du tissu bog-afritex-18', productId: 14},
      { url: '/uploads/products/bog-afritex-18/zoom.png', altText: 'Zoom du tissu bog-afritex-18', productId:14 },
      { url: '/uploads/products/bog-afritex-18/deco.png', altText: 'Deco du tissu bog-afritex-18', productId: 14},
      { url: '/uploads/products/bog-afritex-18/mode.png', altText: 'Mode du tissu bog-afritex-18', productId: 14},
      { url: '/uploads/products/bog-afritex-19/studio.png', altText: 'Studio du tissu bog-afritex-19', productId: 15 },
      { url: '/uploads/products/bog-afritex-19/zoom.png', altText: 'Zoom du tissu bog-afritex-19', productId: 15 },
      { url: '/uploads/products/bog-afritex-19/deco.png', altText: 'Deco du tissu bog-afritex-19', productId: 15 },
      { url: '/uploads/products/bog-afritex-19/mode.png', altText: 'Mode du tissu bog-afritex-19', productId: 15 },
      { url: '/uploads/products/bog-afritex-20/studio.png', altText: 'Studio du tissu bog-afritex-20', productId: 16},
      { url: '/uploads/products/bog-afritex-20/zoom.png', altText: 'Zoom du tissu bog-afritex-20', productId: 16 },
      { url: '/uploads/products/bog-afritex-20/deco.png', altText: 'Deco du tissu bog-afritex-20', productId: 16 },
      { url: '/uploads/products/bog-afritex-20/mode.png', altText: 'Mode du tissu bog-afritex-20', productId: 16 },
      { url: '/uploads/products/bog-afritex-3/studio.png', altText: 'Studio du tissu bog-afritex-3', productId: 17},
      { url: '/uploads/products/bog-afritex-3/zoom.png', altText: 'Zoom du tissu bog-afritex-3', productId: 17},
      { url: '/uploads/products/bog-afritex-3/deco.png', altText: 'Deco du tissu bog-afritex-3', productId: 17 },
      { url: '/uploads/products/bog-afritex-3/mode.png', altText: 'Mode du tissu bog-afritex-3', productId: 17 },
      { url: '/uploads/products/bog-afritex-lourd-2/studio.png', altText: 'Studio du tissu bog-afritex-lourd-2', productId: 19 },
      { url: '/uploads/products/bog-afritex-lourd-2/zoom.png', altText: 'Zoom du tissu bog-afritex-lourd-2', productId: 19},
      { url: '/uploads/products/bog-afritex-lourd-2/deco.png', altText: 'Deco du tissu bog-afritex-lourd-2', productId: 19 },
      { url: '/uploads/products/bog-afritex-lourd-2/mode.png', altText: 'Mode du tissu bog-afritex-lourd-2', productId: 19},
      { url: '/uploads/products/bog-afritex-lourd-5/studio.png', altText: 'Studio du tissu bog-afritex-lourd-5', productId: 21 },
      { url: '/uploads/products/bog-afritex-lourd-5/zoom.png', altText: 'Zoom du tissu bog-afritex-lourd-5', productId: 21 },
      { url: '/uploads/products/bog-afritex-lourd-5/deco.png', altText: 'Deco du tissu bog-afritex-lourd-5', productId: 21 },
      { url: '/uploads/products/bog-afritex-lourd-5/mode.png', altText: 'Mode du tissu bog-afritex-lourd-5', productId: 21 },
      { url: '/uploads/products/bog-afritex-lourd-7/studio.png', altText: 'Studio du tissu bog-afritex-lourd-7', productId: 22 },
      { url: '/uploads/products/bog-afritex-lourd-7/zoom.png', altText: 'Zoom du tissu bog-afritex-lourd-7', productId: 22 },
      { url: '/uploads/products/bog-afritex-lourd-7/deco.png', altText: 'Deco du tissu bog-afritex-lourd-7', productId: 22 },
      { url: '/uploads/products/bog-afritex-lourd-7/mode.png', altText: 'Mode du tissu bog-afritex-lourd-7', productId: 22 },
      { url: '/uploads/products/bog-afritex-lourd-8/studio.png', altText: 'Studio du tissu bog-afritex-lourd-8', productId: 23 },
      { url: '/uploads/products/bog-afritex-lourd-8/zoom.png', altText: 'Zoom du tissu bog-afritex-lourd-8', productId: 23 },
      { url: '/uploads/products/bog-afritex-lourd-8/deco.png', altText: 'Deco du tissu bog-afritex-lourd-8', productId: 23 },
      { url: '/uploads/products/bog-afritex-lourd-8/mode.png', altText: 'Mode du tissu bog-afritex-lourd-8', productId: 23 },
      { url: '/uploads/products/bog-afritex-lourd-9/studio.png', altText: 'Studio du tissu bog-afritex-lourd-9', productId: 24 },
      { url: '/uploads/products/bog-afritex-lourd-9/zoom.png', altText: 'Zoom du tissu bog-afritex-lourd-9', productId: 24 },
      { url: '/uploads/products/bog-afritex-lourd-9/deco.png', altText: 'Deco du tissu bog-afritex-lourd-9', productId: 24 },
      { url: '/uploads/products/bog-afritex-lourd-9/mode.png', altText: 'Mode du tissu bog-afritex-lourd-9', productId: 24 },
      { url: '/uploads/products/mdf-bog-afritex-lourd-1-2-b/studio.png', altText: 'Studio du tissu mdf-bog-afritex-lourd-1-2-b', productId: 26 },
      { url: '/uploads/products/mdf-bog-afritex-lourd-1-2-b/zoom.png', altText: 'Zoom du tissu mdf-bog-afritex-lourd-1-2-b', productId: 26 },
      { url: '/uploads/products/mdf-bog-afritex-lourd-1-2-b/deco.png', altText: 'Deco du tissu mdf-bog-afritex-lourd-1-2-b', productId: 26},
      { url: '/uploads/products/mdf-bog-afritex-lourd-1-2-b/mode.png', altText: 'Mode du tissu mdf-bog-afritex-lourd-1-2-b', productId: 26 },
      { url: '/uploads/products/mdf-bog-afritex-lourd-6/studio.png', altText: 'Studio du tissu mdf-bog-afritex-lourd-6', productId: 25 },
      { url: '/uploads/products/mdf-bog-afritex-lourd-6/zoom.png', altText: 'Zoom du tissu mdf-bog-afritex-lourd-6', productId: 25 },
      { url: '/uploads/products/mdf-bog-afritex-lourd-6/deco.png', altText: 'Deco du tissu mdf-bog-afritex-lourd-6', productId: 25},
      { url: '/uploads/products/mdf-bog-afritex-lourd-6/mode.png', altText: 'Mode du tissu mdf-bog-afritex-lourd-6', productId: 25 },
      { url: '/uploads/products/mdf-bog-new-1/studio.png', altText: 'Studio du tissu mdf-bog-new-1', productId: 27 },
      { url: '/uploads/products/mdf-bog-new-1/zoom.png', altText: 'Zoom du tissu mdf-bog-new-1', productId: 27 },
      { url: '/uploads/products/mdf-bog-new-1/deco.png', altText: 'Deco du tissu mdf-bog-new-1', productId: 27 },
      { url: '/uploads/products/mdf-bog-new-1/mode.png', altText: 'Mode du tissu mdf-bog-new-1', productId: 27 },
      { url: '/uploads/products/mdf-bog-new-2/studio.png', altText: 'Studio du tissu mdf-bog-new-2', productId: 28 },
      { url: '/uploads/products/mdf-bog-new-2/zoom.png', altText: 'Zoom du tissu mdf-bog-new-2', productId: 28 },
      { url: '/uploads/products/mdf-bog-new-2/deco.png', altText: 'Deco du tissu mdf-bog-new-2', productId: 28 },
      { url: '/uploads/products/mdf-bog-new-2/mode.png', altText: 'Mode du tissu mdf-bog-new-2', productId: 28 },
      { url: '/uploads/products/mdf-bog-new-3/studio.png', altText: 'Studio du tissu mdf-bog-new-3', productId:30 },
      { url: '/uploads/products/mdf-bog-new-3/zoom.png', altText: 'Zoom du tissu mdf-bog-new-3', productId: 30},
      { url: '/uploads/products/mdf-bog-new-3/deco.png', altText: 'Deco du tissu mdf-bog-new-3', productId: 30 },
      { url: '/uploads/products/mdf-bog-new-3/mode.png', altText: 'Mode du tissu mdf-bog-new-3', productId: 30 },
      { url: '/uploads/products/mdf-bog-new-4/studio.png', altText: 'Studio du tissu mdf-bog-new-4', productId: 31 },
      { url: '/uploads/products/mdf-bog-new-4/zoom.png', altText: 'Zoom du tissu mdf-bog-new-4', productId: 31},
      { url: '/uploads/products/mdf-bog-new-4/deco.png', altText: 'Deco du tissu mdf-bog-new-4', productId: 31},
      { url: '/uploads/products/mdf-bog-new-4/mode.png', altText: 'Mode du tissu mdf-bog-new-4', productId:31 },
      { url: '/uploads/products/mdf-bog-new-5/studio.png', altText: 'Studio du tissu mdf-bog-new-5', productId: 32 },
      { url: '/uploads/products/mdf-bog-new-5/zoom.png', altText: 'Zoom du tissu mdf-bog-new-5', productId: 32 },
      { url: '/uploads/products/mdf-bog-new-5/deco.png', altText: 'Deco du tissu mdf-bog-new-5', productId: 32 },
      { url: '/uploads/products/mdf-bog-new-5/mode.png', altText: 'Mode du tissu mdf-bog-new-5', productId: 32 },
      { url: '/uploads/products/mdf-bog-new-6/studio.png', altText: 'Studio du tissu mdf-bog-new-6', productId: 33},
      { url: '/uploads/products/mdf-bog-new-6/zoom.png', altText: 'Zoom du tissu mdf-bog-new-6', productId: 33 },
      { url: '/uploads/products/mdf-bog-new-6/deco.png', altText: 'Deco du tissu mdf-bog-new-6', productId: 33 },
      { url: '/uploads/products/mdf-bog-new-6/mode.png', altText: 'Mode du tissu mdf-bog-new-6', productId: 33 },
      { url: '/uploads/products/vint-31/vint-31_studio.jpg', altText: 'Studio du tissu vint-31', productId: 105 },
      { url: '/uploads/products/vint-31/vint-31_zoom.jpg', altText: 'Zoom du tissu vint-31', productId: 105 },
      { url: '/uploads/products/vint-31/vint-31_deco.jpg', altText: 'Deco du tissu vint-31', productId: 105 },
      { url: '/uploads/products/vint-31/vint-31_mode.jpg', altText: 'Mode du tissu vint-31', productId: 105 },
      { url: '/uploads/products/vint-41/vint-41_studio.jpg', altText: 'Studio du tissu vint-41', productId: 117},
      { url: '/uploads/products/vint-41/vint-41_zoom.jpg', altText: 'Zoom du tissu vint-41', productId: 117},
      { url: '/uploads/products/vint-41/vint-41_deco.jpg', altText: 'Deco du tissu vint-41', productId: 117},
      { url: '/uploads/products/vint-41/vint-41_mode.jpg', altText: 'Mode du tissu vint-41', productId: 117},
      { url: '/uploads/products/vint-42/vint-42_studio.jpg', altText: 'Studio du tissu vint-42', productId: 118 },
      { url: '/uploads/products/vint-42/vint-42_zoom.jpg', altText: 'Zoom du tissu vint-42', productId: 118  },
      { url: '/uploads/products/vint-42/vint-42_deco.jpg', altText: 'Deco du tissu vint-42', productId: 118 },
      { url: '/uploads/products/vint-42/vint-42_mode.jpg', altText: 'Mode du tissu vint-42', productId: 118 },
      { url: '/uploads/products/vint-46/vint-46_studio.jpg', altText: 'Studio du tissu vint-46', productId: 120},
      { url: '/uploads/products/vint-46/vint-46_zoom.jpg', altText: 'Zoom du tissu vint-46', productId:120 },
      { url: '/uploads/products/vint-46/vint-46_deco.jpg', altText: 'Deco du tissu vint-46', productId: 120},
      { url: '/uploads/products/vint-46/vint-46_mode.jpg', altText: 'Mode du tissu vint-46', productId: 120},
      { url: '/uploads/products/vint-47/vint-47_studio.jpg', altText: 'Studio du tissu vint-47', productId: 121},
      { url: '/uploads/products/vint-47/vint-47_zoom.jpg', altText: 'Zoom du tissu vint-47', productId: 121},
      { url: '/uploads/products/vint-47/vint-47_deco.jpg', altText: 'Deco du tissu vint-47', productId: 121},
      { url: '/uploads/products/vint-47/vint-47_mode.jpg', altText: 'Mode du tissu vint-47', productId: 121},
      { url: '/uploads/products/vint-51/vint-51_studio.jpg', altText: 'Studio du tissu vint-51', productId: 122 },
      { url: '/uploads/products/vint-51/vint-51_zoom.jpg', altText: 'Zoom du tissu vint-51', productId: 122 },
      { url: '/uploads/products/vint-51/vint-51_deco.jpg', altText: 'Deco du tissu vint-51', productId: 122},
      { url: '/uploads/products/vint-51/vint-51_mode.jpg', altText: 'Mode du tissu vint-51', productId: 122 },
      { url: '/uploads/products/vint-55/vint-55_studio.jpg', altText: 'Studio du tissu vint-55', productId: 124},
      { url: '/uploads/products/vint-55/vint-55_zoom.jpg', altText: 'Zoom du tissu vint-55', productId: 124 },
      { url: '/uploads/products/vint-55/vint-55_deco.jpg', altText: 'Deco du tissu vint-55', productId:  124},
      { url: '/uploads/products/vint-55/vint-55_mode.jpg', altText: 'Mode du tissu vint-55', productId:  124 },
      { url: '/uploads/products/vint-57/vint-57_studio.jpg', altText: 'Studio du tissu vint-57', productId: 125},
      { url: '/uploads/products/vint-57/vint-57_zoom.jpg', altText: 'Zoom du tissu vint-57', productId: 125 },
      { url: '/uploads/products/vint-57/vint-57_deco.jpg', altText: 'Deco du tissu vint-57', productId: 125},
      { url: '/uploads/products/vint-57/vint-57_mode.jpg', altText: 'Mode du tissu vint-57', productId: 125 }
    ],
    skipDuplicates: true
  });

  console.log('✅ Images insérées avec succès.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
